# Generated by Django 2.2.5 on 2022-01-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studynote', '0002_user'),
    ]

    operations = [
    ]
